version: '3'
services:
  icarus-ui:
    container_name: icarus-ui
    image: icarus-ui:latest
    ports:
      - "3000:3000"
  auth-service:
    container_name: auth-service
    image: auth-service:latest
    ports:
      - "8000:8000"
  mongo:
    image: mongo
    volumes:
      - ./data:/data/db
    ports:
      - "27017:27017"